# Generated by Django 3.1.2 on 2020-10-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Personnel_ID', models.IntegerField()),
                ('TimeSlot', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BigProject',
            fields=[
                ('Development', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Funds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LargeScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_ID', models.IntegerField()),
                ('Village_ID', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
                ('Organization_ID', models.IntegerField()),
                ('Development', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LocalPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personnel_ID', models.IntegerField()),
                ('Village_ID', models.IntegerField()),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=20)),
                ('Occupation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_ID', models.IntegerField()),
                ('Organization_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_ID', models.IntegerField()),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('Project_ID', models.IntegerField()),
                ('RequestStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SmallScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_ID', models.IntegerField()),
                ('Village_ID', models.IntegerField()),
                ('Type', models.CharField(max_length=30)),
                ('Personnel_ID', models.IntegerField()),
                ('Facility', models.CharField(max_length=80)),
                ('Location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Village_ID', models.IntegerField()),
                ('Village_name', models.CharField(max_length=80)),
                ('State', models.CharField(max_length=80)),
            ],
        ),
    ]
