# Generated by Django 3.1.2 on 2020-10-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='thumb',
        ),
    ]
