# Generated by Django 3.1.2 on 2020-10-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_community_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='thumb',
            field=models.ImageField(blank=True, default='community.jpg', upload_to=''),
        ),
    ]
