# Generated by Django 3.1.3 on 2020-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201117_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='TimeSlot',
            field=models.DateTimeField(),
        ),
    ]
