# Generated by Django 3.1.3 on 2020-11-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201117_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
